version: '3.8'

services:
  # Базы данных
  logistic-db:
    image: postgres
    container_name: logistic-db
    networks:
      - backend
    environment:
      POSTGRES_DB: logistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - logisticstorage:/var/lib/postgresql/logistic/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  logistic-camunda-db:
    image: postgres
    container_name: logistic-camunda-db
    networks:
      - backend
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - camundastorage:/var/lib/postgresql/camunda/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Инфраструктурные сервисы
  logistic-zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: logistic-zookeeper
    networks:
      - backend
    ports:
      - "2181:2181"
    volumes:
      - zoostorage:/data
    healthcheck:
      test: ["CMD", "echo", "ruok | nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  logistic-kafka:
    image: wurstmeister/kafka:latest
    container_name: logistic-kafka
    networks:
      - backend
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://logistic-kafka:9092,EXTERNAL://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_CONNECT: "logistic-zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - kafkastorage:/kafka
    depends_on:
      logistic-zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Сервисы Spring Cloud
  logistic-configserver:
    image: sergeyignatyuk/logistic-configserver:latest
    container_name: logistic-configserver
    networks:
      - backend
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  logistic-discoveryserver:
    image: sergeyignatyuk/logistic-discoveryserver:latest
    container_name: logistic-discoveryserver
    networks:
      - backend
    ports:
      - "8070:8070"
    depends_on:
      logistic-configserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  logistic-gatewayserver:
    image: sergeyignatyuk/logistic-gatewayserver:latest
    container_name: logistic-gatewayserver
    networks:
      - backend
    ports:
      - "8072:8072"
    depends_on:
      logistic-configserver:
        condition: service_healthy
      logistic-discoveryserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8072/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s

  # Прикладные сервисы
  cargo-contract-service:
    image: sergeyignatyuk/cargo-contract-service:latest
    container_name: cargo-contract-service
    networks:
      - backend
    ports:
      - "8082:8082"
    depends_on:
      logistic-db:
        condition: service_healthy
      logistic-kafka:
        condition: service_healthy
      logistic-configserver:
        condition: service_healthy
      logistic-discoveryserver:
        condition: service_healthy
      logistic-gatewayserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  logistic-bp:
    image: sergeyignatyuk/logistic-bp:latest
    container_name: logistic-bp
    networks:
      - backend
    ports:
      - "8081:8081"
    depends_on:
      logistic-camunda-db:
        condition: service_healthy
      logistic-configserver:
        condition: service_healthy
      logistic-discoveryserver:
        condition: service_healthy
      logistic-gatewayserver:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 35s

  # Вспомогательные сервисы
  logistic-kafka-ui:
    image: obsidiandynamics/kafdrop
    container_name: logistic-kafka-ui
    networks:
      - backend
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "logistic-kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXT_PATH: "/"
    depends_on:
      logistic-kafka:
        condition: service_healthy

networks:
  backend:
    driver: bridge

volumes:
  logisticstorage:
  camundastorage:
  zoostorage:
  kafkastorage:
