spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: cargo-contract-service
            client-secret: 35DwiOq67O34g3drYaX9ZJNIBQGzimqg
            client-name: Cargo Contract Service
            authorization-grant-type: authorization_code
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/logistic-realm
server:
  port: 8082